gText_Birch_Welcome::
	.string "Welcome to RIN.\p"
	.string "It's a big day, today. \p"
	.string "You're finally old enough to have \n"
	.string "your very own POKéMON.\p"
	.string "You can get a POKéMON from\n"
	.string "the lab just south of your house.\p"
	.string "Blue roof. Can't miss it.\p"
	.string "$"

gText_Birch_Pokemon::
	.string "$"

gText_Birch_MainSpeech::
	.string "When people come of age in RIN,\n"
	.string "it's traditional for them to\l"
	.string "strike out into the wilderness on\l"
	.string "an adventure with POKéMON.\p"
	.string "Those who are particularly\n"
	.string "skilled may wish to battle in the\l"
	.string "RIN CHAMPIONSHIP.\p"
	.string "But let's not get ahead of ourselves.\p"
	.string "$"

gText_Birch_AndYouAre::
	.string "First things first. \p"
	.string "$"

gText_Birch_BoyOrGirl::
	.string "Are you a boy?\n"
	.string "Or are you a girl?$"

gText_Birch_WhatsYourName::
	.string "Alright.\n"
	.string "What's your name?$"

gText_Birch_SoItsPlayer::
	.string "So it's {PLAYER}{KUN}?$"

gText_Birch_YourePlayer::
	.string "Ah, okay!\p"
	.string "Welcome to RIN, {PLAYER}{KUN}\p"
	.string "$"

gText_Birch_AreYouReady::
	.string "Your very own adventure is about\n"
	.string "to unfold.\p"
	.string "Take courage, and leap into the\n"
	.string "world of POKéMON where dreams,\l"
	.string "adventure, and friendships await!\p"
	.string "$"
